### ISSUE TITLE
Integrated Strategies?

### ISSUE THREAD

**Issue by ahseeya** [Loli-Killer/ArknightsBattleSimulator#1]
hey, thanks for the mod! everything is working perfectly and it helps me a lot in planning for CM stages.

however im wondering if this mod can be configured to play integrated strategies? i just wanna look on how it'd work out if i have some other operators who're not in my roster yet.

keep up the good work and pls don't feel pressured or anything i just had to ask :')

**Comment by Loli-Killer** [comment]
Not sure if it's coincidence or something but I just started working on it yesterday. I can't promise you when it will come out since I'm lazy and IS2 for some reason has a shit tons of stuffs and variables. I might occasionally post some update in kukki's server if you are in it.

But I'm not sure if I can present you with a totally authentic experience since the map generation/drop rate and such things are determined by the server and since I am proxying arknights to use local server, these values will have to be user-edited.

**Comment by Loli-Killer** [comment]
Also, I might make a new repo instead of updating this one since I'm planning on combine normal and is2 as well as adding a gui for easy editing.

**Comment by ahseeya** [comment]
appreciate the response, nep. i think it'll turn out well either way even if the rng has to be edited imo. it still is a lot of stuff that you've done with the simulator and truthfully it has helped me out a lot in deciding for future gacha pulling haha. hope all turns out well on your side and i wish you well!
